# References: https://www.gitpod.io/docs/references/gitpod-yml
image: gitpod/workspace-postgres

tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev
    env:
      DATABASE_URL: postgres://gitpod@localhost/todos
      
ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode

# Runs everytime code changes on Github, prevents waiting for init script
# to run on each new Gitpod workspace
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
